//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pokupka
    {
        public int IDPokupki { get; set; }
        public Nullable<int> IDSotrudnik { get; set; }
        public Nullable<int> IDProduct { get; set; }
        public string ItogPrise { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Soctrudnic Soctrudnic { get; set; }
    }
}
